### ISSUE TITLE
can no longer persist since latest changes

### ISSUE THREAD

**Issue by vesper8** [jonhue/turbolinks-animate.js#6]
Previously I had this problem https://github.com/jonhue/turbolinks-animate.js/issues/5 where the smooth body fadeout animation would not work if I added my navbar to be persisted.. but at least the navbar did persist throughout the not-smooth transition

since your latest changes, the animation on the body fadeout is smooth but I can no longer persist any elements.

I tried with your version 1.3.4 through 1.3.7 where the nav was persisted, and then 1.3.8 where the same data-turbolinks-animate-persist="true" applied to the same navbar causes the whole body to fadeout and the navbar not to persist

Any idea what's going on?

In 1.3.4 through 1.3.7 it all exhibits the same behaviour.. the nav persists but there is no fadeout when clicking on links.. however if I perform a browser refresh THEN there's a nice smooth fadeout before reloading the page

how can I get that nice smooth fadeout with a persisted navbar ?? I tried adding 

```
    $(document).on('turbolinks:before-visit', function (event) {
        turbolinksAnimateDisappear();
    });
```
  

but to no avail..

**Comment by jonhue** [comment]
@vesper8 Published 1.3.9

**Comment by jonhue** [comment]
@vesper8 

It ended up being a(nother) nasty bug: I omitted an `else` statement and applied animations to the main object, even if persistent elements were present.

A pain to debug ...

**Comment by vesper8** [comment]
@jonhue Really glad you're fixing bugs but unfortunately the very same problem persists.

This brought back the persistent items but unfortunately it still doesn't fadeout when I click around.. same behaviour as before... I'll try to post a video soon

this is all the code I'm using

```
    <header data-turbolinks-animate-persist="true"></header>
```

```
    $(document).on('turbolinks:load', function () {
        $('body').turbolinksAnimate();
        turbolinksAnimateAppear();
    });
    $(document).on('turbolinks:request-start', function () {
        turbolinksAnimateDisappear();
    });
    $(window).on('popstate beforeunload', function (event) {
        turbolinksAnimateDisappear();
    });

```

I would really like to get fadeout animations working as soon as you click a turbolink link.. then it takes the time to fadeout

so weird that it works when you don't persist an element, or when you reload the page manually

**Comment by vesper8** [comment]
please re-open this issue so I don't create a 3rd one on the same problem

**Comment by jonhue** [comment]
@vesper8 Could you check if adding `'fadein'` as an inline animation to your `body` element resolves the problem?

```html
<body data-turbolinks-animate-animation="fadein">
```

**Comment by vesper8** [comment]
adding ```
data-turbolinks-animate-animation="fadein"```

to my body tag produces no changes at all unfortunately.. smooth fadeins but no fadeouts

I still have 
```
 $(document).on('turbolinks:load', function () {
        $('body').turbolinksAnimate();
        turbolinksAnimateAppear();
    });
    $(document).on('turbolinks:request-start', function () {
        turbolinksAnimateDisappear();
    });
    $(window).on('popstate beforeunload', function (event) {
        turbolinksAnimateDisappear();
    });
```

as well right? This part looks good?

**Comment by jonhue** [comment]
@vesper8 

Looks good. Could you verify that you are using the latest 1.3.9, as I am using it in my apps and it is working flawlessly.

**Comment by vesper8** [comment]
Yes I can verify I am using 1.3.9

Since doing a hard-reload does cause the fadeout.. similarly if I click on any links that have the  data-turbolinks="false" set, it also causes the desired effect with a fadeout

But when I click on any links that don't have this (that actually use Turbolinks) then there is no delay for the animation and it immediately hides the current page, skipping the fadeout

**Comment by jonhue** [comment]
@vesper8 

I've just published 2.0 which has a lot of under the hood changes.  Does it fix the issue?

**Comment by vesper8** [comment]
hrmm.. well first of all this introduces breaking changes.. but I made the changes below.. not sure if this is correct since this is not really mentioned in the readme

```
    $(document).on('turbolinks:load', function () {
        TurbolinksAnimate.init();
        TurbolinksAnimate.appear();
        // $('body').turbolinksAnimate();
        // turbolinksAnimateAppear();
    });
    $(document).on('turbolinks:request-start', function () {
        TurbolinksAnimate.disappear();
        // turbolinksAnimateDisappear();
    });
    $(window).on('popstate beforeunload', function (event) {
        TurbolinksAnimate.disappear();
        // turbolinksAnimateDisappear();
    });
```

Does this look ok?

In any case.. I'm afraid this did not fix the behaviour and it is still the same as before.. fadein works but fadeout does not work at all.. except if I do a hard-reload or visit a non-turbolinks link.. just like with 1.3.9

**Comment by jonhue** [comment]
@vesper8 

This is how your code should look like:

```js
$(document).on( 'turbolinks:load', function() {
    TurbolinksAnimate.init();
};
```

I am using this library in my latest app (https://yaeme.com/weather). Everything works well there.
So until you provide something that reproduces the problem, I cannot solve it.
